### ISSUE TITLE
自定义okhttp并没有真正实现啊

### ISSUE THREAD

**Issue by whuhan2013** [wingjay/android-open-source-project-cracking#10]
很多地方都是伪代码，要是有完整的代码就好了。

**Comment by wingjay** [comment]
这里是借以实现的方式来讲解okhttp的设计思想，用伪代码就是为了提取其中的精髓。要看完整代码直接下载okhttp源码不就行了，而且如果把完整代码放到文章中反而失去了重心，学习不到其中的设计思想。

当然，如果有时间，可以自己仿写一个okhttp库。
