### ISSUE TITLE
【推荐】facebook BUCK 构建系统及 BUCK 脚本生成项目 OkBuck

### ISSUE THREAD

**Issue by Piasy** [wingjay/android-open-source-project-cracking#6]
BUCK 是 facebook 开源的比 gradle 更快的构建系统（包括安卓与 iOS），OkBuck 是根据项目当前 gradle 配置自动生成 BUCK 配置脚本的项目。

BUCK 官方首页：https://buckbuild.com/
OkBuck github 主页：https://github.com/Piasy/OkBuck
OkBuck 原理介绍 blog：http://blog.piasy.com/2016/02/01/OkBuck-Underneath-the-hood/

**Comment by wingjay** [comment]
Hi, you can create a pull request with your article.

Please refer to this article for the article style and structure before you upload yours.

https://github.com/wingjay/android-open-source-project-cracking/blob/master/application/Meizhi%20Android%E4%B9%8BRxJava%20%26%20Retrofit%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

Thanks!
